FROM dockerfile/java:oracle-java8

VOLUME /tmp
ADD fhir-adaptor.jar /opt/fhir-adaptor/
EXPOSE 8080
WORKDIR /opt/fhir-adaptor/
CMD ["java", "-Djava.security.egd=file:/dev/./urandom", "-Xms512m", "-Xmx1g", "-jar", "fhir-adaptor.jar"]
